services:
  postgres-test:
    image: postgres:15-alpine
    container_name: techtrend-postgres-test
    environment:
      POSTGRES_DB: techtrend_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_dev_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "127.0.0.1:5434:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: "no"

  redis-test:
    image: redis:7-alpine
    container_name: techtrend-redis-test
    ports:
      - "6380:6379"
    volumes:
      - redis_test_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: "no"

volumes:
  postgres_test_data:
    name: techtrend_postgres_test_data
  redis_test_data:
    name: techtrend_redis_test_data

networks:
  default:
    name: techtrend_test_network