receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins: ["*"]

processors:
  batch: {}
  probabilistic_sampler:
    sampling_percentage: 10

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [probabilistic_sampler, batch]
      exporters: [logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
