receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins: ["*"]

processors:
  batch: {}
  probabilistic_sampler:
    sampling_percentage: 10

exporters:
  logging:
    loglevel: debug
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
  otlphttp/tempo:
    endpoint: http://tempo:4318
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [probabilistic_sampler, batch]
      exporters: [logging, otlphttp/tempo]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, loki]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
