import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

interface FixOptions {
  dryRun: boolean;
  targetIds?: string[];
}

async function fixContaminatedSummaries(options: FixOptions) {
  const { dryRun, targetIds } = options;

  console.log('=== Fix Contaminated Summaries ===');
  console.log(`Mode: ${dryRun ? 'DRY RUN' : 'ACTUAL EXECUTION'}\n`);

  const whereClause = targetIds && targetIds.length > 0
    ? { id: { in: targetIds } }
    : {
        OR: [
          { summary: { contains: '【条件】' } },
          { summary: { contains: '【書き方】' } },
          { summary: { contains: '【文末】' } },
          { summary: { contains: '- 記事の核心的な' } },
          { summary: { contains: '- 技術的価値を' } },
          { summary: { contains: '- 冗長な表現' } },
          { summary: { contains: '[ここに' } },
        ],
      };

  const articles = await prisma.article.findMany({
    where: whereClause,
    select: { id: true, title: true, summary: true },
  });

  console.log(`Found ${articles.length} articles to fix\n`);

  if (dryRun) {
    console.log('Article IDs to be reset:');
    articles.forEach((article, index) => {
      console.log(`  ${index + 1}. ${article.id} - ${article.title.substring(0, 60)}...`);
      console.log(`     Summary preview: ${article.summary.substring(0, 80)}...`);
    });
    console.log('\nRun with --execute flag to actually fix these articles');
    await prisma.$disconnect();
    return;
  }

  let successCount = 0;
  let errorCount = 0;

  for (const article of articles) {
    try {
      await prisma.article.update({
        where: { id: article.id },
        data: {
          summary: '',
          summaryComputedAt: null,
        },
      });
      successCount++;
      console.log(`  ${successCount}. Reset: ${article.id} - ${article.title.substring(0, 60)}...`);
    } catch (error) {
      errorCount++;
      console.error(`  Error: ${article.id} - ${error}`);
    }
  }

  console.log(`\n=== Summary ===`);
  console.log(`Success: ${successCount}`);
  console.log(`Errors: ${errorCount}`);
  console.log(`\nThese articles will be regenerated by the next scheduled summary generation job.`);

  await prisma.$disconnect();
}

const args = process.argv.slice(2);
const dryRun = !args.includes('--execute');
const targetIdsArg = args.find(arg => arg.startsWith('--ids='));
const targetIds = targetIdsArg ? targetIdsArg.split('=')[1].split(',') : undefined;

fixContaminatedSummaries({ dryRun, targetIds }).catch((error) => {
  console.error('Error fixing contaminated summaries:', error);
  process.exit(1);
});
