name: Scheduler - Quality Check & Auto Regenerate

on:
  # TEMPORARILY DISABLED DUE TO PRISMA QUOTA LIMIT (90% reached)
  # schedule:
  #   - cron: '30 6 * * *' # JST 15:30
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type 'YES' to confirm manual execution (DB quota risk)"
        required: true
        type: string
        default: "NO"

concurrency:
  group: techtrend-scheduler-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality-auto:
    if: github.event_name != 'workflow_dispatch' || (github.event_name == 'workflow_dispatch' && github.event.inputs.confirm == 'YES')
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Generate Prisma Client
        run: npx prisma generate
      - name: Apply DB migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma migrate deploy
      - name: Run quality check and auto-regenerate
        env:
          NODE_ENV: production
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          npx tsx scripts/scheduled/quality-check.ts --days 7 --auto-regenerate
          npx tsx scripts/scheduled/auto-regenerate-low-quality.ts --threshold 70 --limit 10
