name: Scheduler - RSS Feeds

on:
  schedule:
    # Run 3 times a day: 7:00, 13:00, 19:00 JST (22:00, 04:00, 10:00 UTC)
    - cron: '0 22 * * *' # 7:00 JST
    - cron: '0 4 * * *'  # 13:00 JST
    - cron: '0 10 * * *' # 19:00 JST
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type 'YES' to confirm manual execution"
        required: true
        type: string
        default: "NO"

concurrency:
  group: techtrend-scheduler-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rss-hourly:
    if: github.event_name != 'workflow_dispatch' || (github.event_name == 'workflow_dispatch' && github.event.inputs.confirm == 'YES')
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Generate Prisma Client
        run: npx prisma generate
      - name: Apply DB migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma migrate deploy
      - name: Collect RSS sources and post-process
        env:
          NODE_ENV: production
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          npx tsx scripts/scheduled/collect-feeds.ts "はてなブックマーク" "Zenn" "Dev.to" "Publickey" "Stack Overflow Blog" "Think IT" "Rails Releases" "AWS" "SRE" "Google Developers Blog" "Corporate Tech Blog" "Hugging Face Blog" "Google AI Blog" "InfoQ Japan" "GitHub Blog" "Cloudflare Blog" "Mozilla Hacks" "Hacker News" "Medium Engineering"
          npx tsx scripts/scheduled/manage-summaries.ts generate
          npx tsx scripts/scheduled/manage-quality-scores.ts calculate
          npx tsx scripts/scheduled/calculate-difficulty-levels.ts
