name: Scheduler - Daily Summaries

on:
  schedule:
    - cron: '30 1 * * *' # JST 10:30
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type 'YES' to confirm manual execution (DB quota risk)"
        required: true
        type: string
        default: "NO"

concurrency:
  group: techtrend-scheduler-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  daily-summaries:
    if: github.event_name != 'workflow_dispatch' || (github.event_name == 'workflow_dispatch' && github.event.inputs.confirm == 'YES')
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Generate Prisma Client
        run: npx prisma generate
      - name: Apply DB migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma migrate deploy
      - name: Generate summaries and post-process
        env:
          NODE_ENV: production
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          # Summary generation is now handled by scheduler-rss-hourly to consolidate DB operations
          # npx tsx scripts/scheduled/manage-summaries.ts generate
          npx tsx scripts/scheduled/manage-quality-scores.ts calculate
          npx tsx scripts/scheduled/calculate-difficulty-levels.ts
