name: Scheduler - Tags Twice Daily

on:
  schedule:
    - cron: '30 11 * * *' # JST 20:30 (UTC 11:30) - Reduced from twice daily to save DB operations
  workflow_dispatch:

concurrency:
  group: techtrend-scheduler-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  tags:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Generate Prisma Client
        run: npx prisma generate
      - name: Apply DB migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma migrate deploy
      - name: Generate tags
        env:
          NODE_ENV: production
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
        run: |
          npx tsx scripts/scheduled/generate-tags.ts
