name: Scheduler - Daily Cleanup

on:
  schedule:
    - cron: '0 13 * * *' # JST 22:00
  workflow_dispatch:

concurrency:
  group: techtrend-scheduler-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Generate Prisma Client
        run: npx prisma generate
      - name: Apply DB migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma migrate deploy
      - name: Cleanup tasks
        env:
          NODE_ENV: production
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
        run: |
          npx tsx scripts/scheduled/delete-low-quality-articles.ts
          npx tsx scripts/scheduled/clean-tags.ts
