name: Scheduler - Tags Twice Daily

on:
  schedule:
    - cron: '30 23 * * *' # JST 08:30 (previous day 23:30 UTC)
    - cron: '30 11 * * *' # JST 20:30
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type 'YES' to confirm manual execution"
        required: true
        type: string
        default: "NO"

concurrency:
  group: techtrend-scheduler-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tags:
    if: github.event_name != 'workflow_dispatch' || (github.event_name == 'workflow_dispatch' && github.event.inputs.confirm == 'YES')
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Generate Prisma Client
        run: npx prisma generate
      - name: Apply DB migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma migrate deploy
      - name: Generate tags
        env:
          NODE_ENV: production
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
        run: |
          npx tsx scripts/scheduled/generate-tags.ts
