name: Scheduler - Daily Cleanup

on:
  # TEMPORARILY DISABLED DUE TO PRISMA QUOTA LIMIT (90% reached)
  # schedule:
  #   - cron: '0 13 * * *' # JST 22:00
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type 'YES' to confirm manual execution (DB quota risk)"
        required: true
        type: string
        default: "NO"

concurrency:
  group: techtrend-scheduler-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cleanup:
    if: github.event_name != 'workflow_dispatch' || inputs.confirm == 'YES'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Generate Prisma Client
        run: npx prisma generate
      - name: Apply DB migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma migrate deploy
      - name: Cleanup tasks
        env:
          NODE_ENV: production
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
        run: |
          npx tsx scripts/scheduled/delete-low-quality-articles.ts
          npx tsx scripts/scheduled/clean-tags.ts
