name: Scheduler - Qiita Popular Twice Daily

on:
  schedule:
    - cron: '5 20 * * *' # JST 05:05 (previous day 20:05 UTC)
    - cron: '5 8 * * *' # JST 17:05
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type 'YES' to confirm manual execution (DB quota risk)"
        required: true
        type: string
        default: "NO"

concurrency:
  group: techtrend-scheduler-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  qiita-popular:
    if: github.event_name != 'workflow_dispatch' || (github.event_name == 'workflow_dispatch' && github.event.inputs.confirm == 'YES')
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Generate Prisma Client
        run: npx prisma generate
      - name: Apply DB migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma migrate deploy
      - name: Collect Qiita Popular and post-process
        env:
          NODE_ENV: production
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          npx tsx scripts/scheduled/collect-feeds.ts "Qiita Popular"
          npx tsx scripts/scheduled/manage-summaries.ts generate
          npx tsx scripts/scheduled/manage-quality-scores.ts calculate
          npx tsx scripts/scheduled/calculate-difficulty-levels.ts
